export type GoalId = 'career' | 'finance' | 'confidence' | 'health' | 'love' | 'growth';

export interface Goal {
  id: GoalId;
  label: string;
  icon: string;
}

export const GOALS: Goal[] = [
  { id: 'career', label: 'Career Success', icon: 'target' },
  { id: 'finance', label: 'Financial Freedom', icon: 'star' },
  { id: 'confidence', label: 'Confidence', icon: 'sparkle' },
  { id: 'health', label: 'Better Health', icon: 'wind' },
  { id: 'love', label: 'Better Relationships', icon: 'heart' },
  { id: 'growth', label: 'Personal Growth', icon: 'sun' },
];

export const AFFIRMATIONS: Record<GoalId, string[]> = {
  confidence: [
    'I am becoming the person I aspire to be.',
    'I trust myself to handle whatever comes.',
    'My confidence grows with every quiet step I take.',
    'I belong in every room I choose to enter.',
    'My voice matters, and I speak it with calm.',
    'I am enough, exactly as I am right now.',
    'I meet doubt with patience and keep moving.',
    'I am proud of how far I have already come.',
    'I stand tall in who I am becoming.',
    'I let go of the need for everyone to approve.',
    'My worth is not up for debate.',
    'I trust the quiet strength within me.',
    'I act with courage even when I feel unsure.',
    'I treat myself with the kindness I deserve.',
    'I am steady, capable, and grounded.',
    'I release comparison and honor my own path.',
    'Every challenge shows me how strong I am.',
    'I speak to myself like someone I love.',
    'I carry myself with quiet self-respect.',
    'I am allowed to take up space.',
    'My past does not define what I can do next.',
    'I choose self-belief over self-doubt today.',
    'I am learning to trust my own decisions.',
    'I am calm under pressure and clear in my mind.',
    'I forgive my mistakes and grow from them.',
    'I deserve good things and I welcome them in.',
    'I am resilient; I rise after every setback.',
    'My confidence is built one honest step at a time.',
    'I honor my needs without apology.',
    'I am exactly where I need to be to grow.',
    'I do not shrink to make others comfortable.',
    'My presence has value before I say a word.',
    'I keep my promises to myself.',
    'I can be nervous and still do it anyway.',
    'I trust that I will figure things out as I go.',
    'I no longer wait for permission to begin.',
    'I am not behind; I am on my own timeline.',
    'I let my actions speak louder than my fear.',
    'I am worthy of respect, including my own.',
    'I hold my head up even on uncertain days.',
    'I am the calm in my own storm.',
    'I trust my instincts a little more each day.',
    'I am not defined by anyone else’s opinion of me.',
    'I give myself credit simply for trying.',
    'I am steady even when things around me are not.',
    'I choose courage in small, ordinary moments.',
    'I am allowed to change my mind.',
    'I meet myself with patience, not judgment.',
    'I have survived every hard day so far.',
    'I am quietly sure of who I am.',
    'I walk into the room and let my shoulders drop.',
    'I am unstoppable when I trust my own pace.',
    'My opinion is allowed to be different and still right for me.',
    'I am a force when I stop asking for permission.',
    'I soften my inner critic and speak to myself with respect.',
    'I am magnetic when I simply show up as myself.',
    'I choose self-trust over self-doubt, on repeat.',
    'I am bold enough to be seen exactly as I am.',
    'I stand steady, breathe slow, and begin.',
    'Fear does not get the final say in my life.',
    'I claim my space without shrinking for anyone.',
    'I am calm proof that confidence doesn\'t have to be loud.',
    'I release the urge to explain myself to everyone.',
    'I am fearless in the pursuit of who I want to be.',
    'My self-worth is settled, not up for negotiation.',
    'I am the kind of strong that doesn\'t need an audience.',
    'I carry myself like someone who belongs.',
    'I am worthy of taking the credit I have earned.',
    'I trust the version of me that keeps showing up.',
    'I am radiant when I stop apologizing for existing.',
    'Every room gets a little better when I walk in steady.',
    'I am gentle with the parts of me still building courage.',
    'I have everything I need to handle today.',
    'I am proof that quiet confidence still wins.',
    'I am allowed to be proud out loud.',
    'I back myself.',
    'Confidence looks good on me.',
    'I show up anyway.',
    'I was built for hard things.',
    'My energy speaks before I do.',
    'I choose myself today.',
    'I am not for everyone, and that is fine.',
    'I rise. Every time.',
    'Today, I bet on me.',
    'I believe in who I am becoming.',
  ],
  career: [
    'I am building work that gives my days meaning.',
    'Opportunity moves toward my steady, focused effort.',
    'I lead with clarity and a calm, certain mind.',
    'My focus turns effort into real progress.',
    'I bring value to everything I touch.',
    'I am open to opportunities I cannot yet see.',
    'I do meaningful work, one focused hour at a time.',
    'My skills grow sharper with steady practice.',
    'I handle challenges with patience and creativity.',
    'I am worthy of the success I am building.',
    'I set clear goals and move toward them daily.',
    'I trust my ability to learn what I need.',
    'I work with purpose, not just urgency.',
    'I make decisions with confidence and care.',
    'My consistency is quietly building my future.',
    'I attract collaborators who respect my work.',
    'I turn setbacks into lessons that serve me.',
    'I am calm, capable, and ready for what comes.',
    'I deserve to be recognized for my contributions.',
    'I protect my energy for the work that matters.',
    'I am growing into the leader I want to be.',
    'I trust the timing of my career.',
    'My ambition and my peace can coexist.',
    'I finish what I start with steady resolve.',
    'I am resourceful and I find a way forward.',
    'Each focused day compounds into mastery.',
    'I welcome feedback as a path to growth.',
    'I create more than I consume.',
    'I am building something I am proud of.',
    'My best work comes from a calm, clear mind.',
    'I am allowed to want more than I have.',
    'I show up fully, even when no one is watching.',
    'My effort today is an investment in my future.',
    'I do not rush; I build to last.',
    'I am becoming undeniable at my craft.',
    'I say no to what pulls me off course.',
    'I learn faster than I fall behind.',
    'I stay calm when the plan changes.',
    'I begin before I feel ready and trust the rest.',
    'My work quietly speaks for itself.',
    'I deserve a seat at the table I am building.',
    'I keep going long after the motivation fades.',
    'I am patient with the slow climb.',
    'I turn pressure into focus.',
    'I am proud of the discipline I am building.',
    'I make today count, one task at a time.',
    'I am worthy of work that fulfills me.',
    'I let small wins carry me forward.',
    'I am the person who makes things happen.',
    'I trust that consistent effort always pays off.',
    'I attract opportunities that match my real potential.',
    'I am the kind of person people want on their team.',
    'My calm focus gets more done than my anxious hustle ever did.',
    'I am becoming the expert I once admired from a distance.',
    'I release the pressure to have it all figured out by now.',
    'I am sharp, capable, and ready for the next challenge.',
    'Every skill I practice becomes a tool I can rely on.',
    'I am the leader of my own professional path.',
    'I walk into hard conversations with a steady, clear voice.',
    'I am worthy of the title I am working toward.',
    'My ideas are valuable, and I say them out loud.',
    'I am unstoppable when I stop waiting to feel ready.',
    'I choose depth over busyness in my work.',
    'I am building a reputation I would trust myself.',
    'I am magnetic to the right opportunities, not just any.',
    'I let go of comparing my timeline to anyone else\'s.',
    'I am capable of learning whatever this next step requires.',
    'My focus is a skill, and I am sharpening it daily.',
    'I am the person who delivers when it counts.',
    'I am open to the career I haven\'t imagined yet.',
    'Each small win is quietly building my reputation.',
    'I am driven, but I am not in a hurry.',
    'I trust that my work speaks even when I stay quiet.',
    'I am becoming someone whose name means something in this field.',
    'I show up prepared, and preparation is its own confidence.',
    'I am great at what I do.',
    'My work matters.',
    'I get better every single day.',
    'Big things are coming my way.',
    'I was made for this work.',
    'I focus. I finish. I deliver.',
    'Success is a habit I practice daily.',
    'I am one focused hour away from progress.',
    'Doors open for people who keep knocking.',
    'I earn my own luck.',
  ],
  finance: [
    'I am creating lasting abundance through patience.',
    'I give money direction, and it follows my intention.',
    'My future self is grateful for the choices I make today.',
    'I am a careful, confident steward of my money.',
    'Abundance flows to me through honest effort.',
    'I make calm, wise decisions with my finances.',
    'I am building wealth one steady choice at a time.',
    'I spend in line with what truly matters to me.',
    'I release fear and approach money with clarity.',
    'I am worthy of financial security and ease.',
    'Every dollar I save is a vote for my freedom.',
    'I trust myself to manage what I earn.',
    'I am patient; wealth grows slowly and surely.',
    'I welcome new sources of income with openness.',
    'I am free from comparison about money.',
    'I give generously from a place of plenty.',
    'My habits today shape my freedom tomorrow.',
    'I am grounded and calm about my finances.',
    'I deserve to enjoy the fruits of my work.',
    'I plan ahead and my future feels secure.',
    'I am learning more about money every day.',
    'I let go of guilt and make peace with money.',
    'I attract opportunities to grow my resources.',
    'I live within my means and still feel rich.',
    'My relationship with money is calm and healthy.',
    'I am building a foundation that lasts.',
    'I make room for abundance by spending wisely.',
    'I trust that I will always have enough.',
    'I invest in my future with quiet confidence.',
    'Financial freedom is a path I walk daily.',
    'I am calm and clear when I look at my money.',
    'I am allowed to build wealth without guilt.',
    'I make my money work for the future, not just today.',
    'I am patient with the slow growth of savings.',
    'Every wise choice compounds in my favor.',
    'I face my finances with honesty, not fear.',
    'I handle money with a clear head.',
    'I value security over impressing anyone.',
    'I stay steady through the ups and downs of money.',
    'I deserve a life of comfort and real choice.',
    'I spend with intention and rest with ease.',
    'I am building freedom one small habit at a time.',
    'Money is a tool, and I use it with care.',
    'I release shame and learn what I do not yet know.',
    'I am open to earning in ways I have not tried.',
    'I trust my future self will thank me for this.',
    'I make peace with money and it makes peace with me.',
    'I am worthy of more than just getting by.',
    'Small savings today buy calm tomorrow.',
    'I am the author of my own financial story.',
    'I am disciplined with money, and it shows.',
    'My bank balance reflects my growing discipline, not my luck.',
    'I am a magnet for income I haven\'t even imagined yet.',
    'I choose long-term ease over short-term impulse.',
    'I am worthy of wealth built honestly and steadily.',
    'Every smart choice today is a gift to my future self.',
    'I am unstoppable in building the life I can actually afford.',
    'I release the old story that money is something to fear.',
    'My relationship with money gets calmer with every paycheck.',
    'I am open to abundance arriving in ways I didn\'t plan.',
    'I am the architect of my own financial freedom.',
    'My budget is a plan for freedom, and I follow it.',
    'I am building wealth that outlasts any single bad month.',
    'I am a magnet for opportunities that pay me what I\'m worth.',
    'My net worth grows every time I choose patience over panic.',
    'I am becoming financially fluent, one decision at a time.',
    'I deserve a bank account that lets me breathe easy.',
    'I am bold enough to ask for what I\'m worth.',
    'I respect money, and it works for me.',
    'I let go of guilt every time I spend with intention.',
    'I am calm in the face of every bill, every number.',
    'I am building a life where money brings peace, not stress.',
    'I am capable of turning small habits into real security.',
    'I trust that my effort and my income will eventually align.',
    'I am the kind of wealthy that feels like peace, not pressure.',
    'Money flows to me with ease.',
    'I am good with money.',
    'Wealth is a habit, and I have it.',
    'My savings grow while I sleep.',
    'I always have more than enough.',
    'Abundance is my natural state.',
    'I attract wealth by creating value.',
    'Every dollar I own has a purpose.',
    'Financial freedom is already on its way.',
    'I am rich in options and choices.',
  ],
  health: [
    'My body grows stronger and calmer each day.',
    'Every breath restores the energy I need.',
    'I honor my body with rest, movement, and care.',
    'I listen to what my body is telling me.',
    'I nourish myself with food that gives me life.',
    'I move my body in ways that feel good.',
    'Rest is productive, and I allow myself to rest.',
    'I am gentle with myself on hard days.',
    'My health is built through small daily choices.',
    'I breathe deeply and let tension melt away.',
    'I treat my body as a home worth caring for.',
    'I drink water and feel my energy return.',
    'Sleep heals me, and I welcome it fully.',
    'I am patient with my body as it heals.',
    'I choose calm over stress whenever I can.',
    'My mind grows quieter with every slow breath.',
    'I am grateful for all my body does for me.',
    'I make space for stillness in my day.',
    'I release what I cannot control and breathe.',
    'Movement is a gift I give myself.',
    'I am steadily building strength and calm.',
    'I forgive my body and thank it instead.',
    'I let go of tension in my shoulders and jaw.',
    'I deserve to feel rested and well.',
    'I care for my mind as gently as my body.',
    'Each healthy choice makes the next one easier.',
    'I am present in my body, here and now.',
    'I give myself permission to slow down.',
    'My energy renews with rest and good care.',
    'I am healing, growing, and feeling more alive.',
    'I treat rest as part of getting stronger.',
    'I am allowed to slow down and still feel okay.',
    'My body is doing its best for me right now.',
    'I choose nourishment over punishment.',
    'I let my breath bring me back to calm.',
    'I am building health I can feel, not just see.',
    'I give my mind the same care I give my body.',
    'I move because I can, not because I must.',
    'I unclench, I soften, I let go.',
    'I am patient with my own healing.',
    'I deserve sleep that truly restores me.',
    'I drink water and feel myself wake up.',
    'I trust my body to know what it needs.',
    'I set the day down before I rest.',
    'I am gentle with myself when I am tired.',
    'Each calm breath softens my whole body.',
    'Small choices add up to lasting well-being.',
    'I am present in this moment, simply breathing.',
    'I offer my body kindness instead of criticism.',
    'I am allowed to rest without earning it first.',
    'I feel my shoulders drop with every slow exhale.',
    'I am becoming someone who chooses rest without guilt.',
    'My body is strong enough for the life I am building.',
    'I am committed to feeling well, one day at a time.',
    'I release the tightness I\'ve been carrying all day.',
    'I trust my body\'s signals more than anyone else\'s opinion.',
    'I am radiant with the energy of a well-rested mind.',
    'Every glass of water is a small act of self-respect.',
    'I am capable of healing at exactly the pace I need.',
    'My breath is the one thing always within my control.',
    'I am powerful enough to choose rest over hustle.',
    'I let warmth spread through my chest with every deep breath.',
    'I am becoming gentler with my body, not harsher.',
    'I am worthy of a body that feels like home.',
    'My energy returns the moment I stop forcing it.',
    'I am strong, steady, and exactly where I need to be.',
    'I choose movement that feels like joy, not punishment.',
    'I am calm enough to hear what my body actually needs.',
    'Each deep breath is proof I am taking care of myself.',
    'My strength is quiet, steady, and real.',
    'I deserve to feel good in my own skin today.',
    'I am open to healing in ways I haven\'t tried yet.',
    'My body and my mind are finally on the same team.',
    'I am vibrant, even on the days I move slowly.',
    'Stillness is not laziness; it is repair.',
    'My body is on my side.',
    'I feel a little better every day.',
    'Rest is my superpower.',
    'I breathe in calm and breathe out stress.',
    'Energy follows care, and I care for myself.',
    'I am healthy, whole, and healing.',
    'One deep breath changes everything.',
    'My mind is clear. My body is calm.',
    'I move, I rest, I recover.',
    'Health is something I do daily.',
  ],
  love: [
    'I give and receive love with an open heart.',
    'I attract people who value exactly who I am.',
    'I am fully present for the ones I love.',
    'I am worthy of deep and gentle love.',
    'I let people see the real me.',
    'I listen with patience and an open mind.',
    'I bring warmth to every connection I make.',
    'I release old hurt to make room for love.',
    'I love myself first, and love others from there.',
    'I communicate my needs with honesty and care.',
    'I am surrounded by people who lift me up.',
    'I forgive easily and hold grudges lightly.',
    'I show up for the people who matter to me.',
    'I am safe to be open and tender.',
    'I trust the right people to stay.',
    'I give kindness without keeping score.',
    'I am patient with those I love, and with myself.',
    'I deserve relationships that feel like peace.',
    'I welcome love into my life with open arms.',
    'I speak gently, even in disagreement.',
    'I let love in without fear of losing it.',
    'My presence is a gift to those around me.',
    'I nurture my friendships with time and care.',
    'I am loved more than I often realize.',
    'I set kind boundaries that protect my heart.',
    'I choose connection over perfection.',
    'I appreciate the people in my life today.',
    'I am open, warm, and easy to love.',
    'I give the love I wish to receive.',
    'My heart grows softer and braver each day.',
    'I love others without losing myself.',
    'I am safe to need other people.',
    'I choose people who choose me back.',
    'I let love be easy when it wants to be.',
    'I show up softer than my fear tells me to.',
    'I am worthy of being chosen, not just useful.',
    'I give space and take space, with care.',
    'I am gentle with the people learning to love me.',
    'I let the right people in slowly and surely.',
    'I am loved in ways I am only beginning to see.',
    'I lead with warmth, even when I am unsure.',
    'I do not have to be perfect to be loved.',
    'I let go of love that asks me to be smaller.',
    'I am present for the small, ordinary moments.',
    'I trust that the right people will stay.',
    'I speak my love out loud while I can.',
    'I am patient with the people I care about.',
    'I am a safe place for the people I love.',
    'I choose tenderness, again and again.',
    'I deserve a love that feels like rest.',
    'I am becoming someone who loves without losing myself.',
    'My heart is open, but my boundaries are clear.',
    'I am a magnet for love that feels easy, not exhausting.',
    'I release relationships that ask me to disappear.',
    'I am worthy of being chosen exactly as I am.',
    'I choose people who make space for the real me.',
    'I love deeply and without apology.',
    'My presence is enough; I don\'t have to perform for love.',
    'I am bold enough to say what I need from the people I love.',
    'I trust that the right connections will feel like ease.',
    'I am open to a love that feels like coming home.',
    'Every honest conversation makes my relationships stronger.',
    'I am radiant in the way I show up for people I care about.',
    'I let go of love that costs me my peace.',
    'I am capable of repairing, not just avoiding, conflict.',
    'My love is generous, but it is not unlimited.',
    'I am a safe harbor for the people who trust me.',
    'I deserve a love that doesn\'t require me to shrink.',
    'I am becoming braver in how openly I love.',
    'I choose softness even when guarding myself would be easier.',
    'I am magnetic to connection because I show up as myself.',
    'My friendships deserve the same care I give new love.',
    'I am worthy of love that doesn\'t keep score.',
    'I trust the quiet, steady kind of love over the dramatic kind.',
    'I choose connection, even when hiding feels safer.',
    'I am easy to love.',
    'Love finds me everywhere I go.',
    'I attract warm, honest people.',
    'My heart is open and safe.',
    'I give love freely, and it returns.',
    'The right people feel like home.',
    'I deserve love that stays.',
    'I am someone worth choosing.',
    'Real love starts with how I treat myself.',
    'Connection comes naturally to me.',
  ],
  growth: [
    'Each day I move a little closer to my best self.',
    'I welcome change as the path to who I am becoming.',
    'I am patient and kind with my own becoming.',
    'I grow a little every single day.',
    'I embrace discomfort as a sign of growth.',
    'I am curious, open, and willing to learn.',
    'Mistakes are lessons, and I am learning well.',
    'I let go of who I was to become who I am.',
    'I am building better habits one day at a time.',
    'I trust the slow work of becoming.',
    'I choose progress over perfection.',
    'I am proud of the small steps I take.',
    'I stay open to new ideas and perspectives.',
    'Every day is a chance to begin again.',
    'I release the need to have it all figured out.',
    'I am exactly where I need to be in my journey.',
    'I turn challenges into stepping stones.',
    'I give myself grace as I grow.',
    'I am becoming wiser with every experience.',
    'I welcome feedback that helps me improve.',
    'My potential is not fixed; it expands.',
    'I show up for myself, even imperfectly.',
    'I celebrate how far I have come.',
    'I am planting seeds that will bloom in time.',
    'I choose growth even when it is hard.',
    'I am gentle with the parts of me still learning.',
    'Small, steady effort changes everything.',
    'I trust myself to keep moving forward.',
    'I am open to becoming more than I am today.',
    'Every quiet step forward is worth taking.',
    'I am a work in progress, and that is enough.',
    'I let go of who I thought I should be.',
    'I grow through what I go through.',
    'I am allowed to outgrow old versions of me.',
    'I trust the timing of my own becoming.',
    'I am not failing; I am learning.',
    'I choose what is right over what is easy.',
    'I get a little braver every day.',
    'I am patient with the parts of me still healing.',
    'I let discomfort teach me what I need to know.',
    'I am becoming someone I am proud of.',
    'I show up even on the days I do not feel like it.',
    'I trade perfection for honest progress.',
    'I am open to becoming, not just being.',
    'I keep the promises I make to my future self.',
    'I let go of the timeline I was supposed to follow.',
    'I am learning to enjoy the climb.',
    'Every small effort is shaping who I become.',
    'I forgive the version of me who did not know better.',
    'I am exactly as far along as I am meant to be.',
    'I am becoming, one imperfect day at a time.',
    'Every uncomfortable moment is quietly making me stronger.',
    'I am unstoppable in my refusal to stay the same.',
    'I release the version of me who settled for less.',
    'I am capable of more than my doubts let me believe.',
    'My growth doesn\'t need to be loud to be real.',
    'I am bold enough to start again, however many times it takes.',
    'I choose curiosity over comfort, again and again.',
    'I am becoming someone my future self will thank me for.',
    'Every lesson I survive becomes a tool I keep.',
    'I am radiant proof that change is always possible.',
    'I let go of the need to arrive somewhere finished.',
    'I am open to growth I cannot yet picture.',
    'My patience with myself is its own kind of progress.',
    'I am unbreakable in the slow, steady climb forward.',
    'I am exactly the work in progress I am meant to be.',
    'I trust that discomfort today is growth in disguise.',
    'I am bold enough to outgrow rooms that no longer fit.',
    'Every small habit is quietly rewriting who I am.',
    'I am becoming wiser with every version of myself I release.',
    'I choose growth even when staying the same feels safer.',
    'I am capable of change that lasts longer than motivation.',
    'My story isn\'t finished, and that excites me.',
    'I am gentle with how long becoming actually takes.',
    'I am unstoppable, not because it\'s easy, but because I keep going.',
    'I am growing, even when I can\'t see it.',
    'Better every day. That is the deal.',
    'I outgrow. I evolve. I rise.',
    'Growth is my default setting.',
    'Today I am one percent better.',
    'I turn pain into progress.',
    'The best version of me is already forming.',
    'I bloom in my own season.',
    'Change is my friend, not my enemy.',
    'I keep going. That is the whole secret.',
  ],
};

// Combined, de-duplicated pool of affirmations across ALL selected goals,
// interleaved round-robin (one from each goal in turn) so a multi-goal user's
// feed is mixed rather than running through one goal's full set before the
// next. Falls back to 'confidence' when no goal is selected.
export function affirmationPool(goals: GoalId[]): string[] {
  const ids = goals.length ? goals : (['confidence'] as GoalId[]);
  const seen = new Set<string>();
  const pool: string[] = [];
  const maxLen = Math.max(...ids.map((id) => AFFIRMATIONS[id].length));
  for (let i = 0; i < maxLen; i++) {
    for (const id of ids) {
      const text = AFFIRMATIONS[id][i];
      if (text && !seen.has(text)) {
        seen.add(text);
        pool.push(text);
      }
    }
  }
  return pool;
}

// Built once at module load: text -> goal id, so goalIdForAffirmation is an
// O(1) lookup instead of an O(goals * affirmations) scan per call.
const AFFIRMATION_TO_GOAL: Map<string, GoalId> = (() => {
  const map = new Map<string, GoalId>();
  for (const id of Object.keys(AFFIRMATIONS) as GoalId[]) {
    for (const text of AFFIRMATIONS[id]) {
      map.set(text, id);
    }
  }
  return map;
})();

// Reverse-lookup the goal an affirmation belongs to (for the ✦ goal tag).
export function goalIdForAffirmation(text: string): GoalId | undefined {
  return AFFIRMATION_TO_GOAL.get(text);
}

export const REMINDER_OPTIONS = [
  { id: 'morning', label: 'Morning', time: '7:00 – 9:00 AM', icon: 'sun' },
  { id: 'afternoon', label: 'Afternoon', time: '12:00 – 2:00 PM', icon: 'target' },
  { id: 'evening', label: 'Evening', time: '7:00 – 9:00 PM', icon: 'moon' },
] as const;

export type ReminderTime = (typeof REMINDER_OPTIONS)[number]['id'];

// Canonical chronological order, used to normalize a set of picked times.
const REMINDER_ORDER = REMINDER_OPTIONS.map((o) => o.id);

// Sort a set of reminder times into morning → afternoon → evening order.
export function sortReminderTimes(times: ReminderTime[]): ReminderTime[] {
  return [...times].sort((a, b) => REMINDER_ORDER.indexOf(a) - REMINDER_ORDER.indexOf(b));
}

export const SOUNDS = [
  { id: 'rain', label: 'Rain', icon: 'rain' },
  { id: 'ocean', label: 'Ocean', icon: 'ocean' },
  { id: 'forest', label: 'Forest', icon: 'forest' },
] as const;

export type SoundId = 'rain' | 'ocean' | 'forest';

export const FOCUS_DURATIONS = [15, 25, 45] as const;
// Presets above are 15/25/45, but a custom duration (any whole number of
// minutes) can also be picked via the duration wheel on the Focus screen.
export type FocusDuration = number;

export const PAYWALL_PLANS = [
  {
    id: 'weekly',
    label: 'Weekly',
    price: '$2.99/week',
    note: '3-day free trial',
    badge: null,
  },
  {
    id: 'annual',
    label: 'Annual',
    price: '$39.99/year',
    note: '7-day free trial · $3.33/mo',
    badge: 'Most Popular',
  },
  {
    id: 'monthly',
    label: 'Monthly',
    price: '$7.99/month',
    note: 'Billed monthly',
    badge: null,
  },
  {
    id: 'lifetime',
    label: 'Lifetime',
    price: '$99.99 once',
    note: 'Pay once, yours forever',
    badge: null,
  },
] as const;

// Single source of truth for a plan's free-trial length: parsed from the plan's
// `note` copy above (e.g. "3-day free trial", "7-day free trial · $3.33/mo").
// Returns the day count for trial-bearing plans, or null for plans with no
// trial (monthly, lifetime). Keep trial lengths defined only in PAYWALL_PLANS so
// UI copy never drifts from a second hardcoded source.
export function trialDaysForPlan(planId: string): number | null {
  const note = PAYWALL_PLANS.find((p) => p.id === planId)?.note ?? '';
  const match = note.match(/(\d+)-day free trial/);
  return match ? Number(match[1]) : null;
}

export const PAYWALL_FEATURES = [
  { icon: 'sparkle', text: 'Unlimited personalized affirmations' },
  { icon: 'focus', text: 'Every focus length & ambient sound' },
  { icon: 'progress', text: 'Full activity history & insights' },
];